# Generated by Django 4.1.5 on 2023-01-15 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addedTime', models.DateTimeField()),
                ('destination', models.CharField(max_length=100)),
            ],
        ),
    ]
