# Generated by Django 4.1.5 on 2023-01-15 17:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_trip_departuredate"),
    ]

    operations = [
        migrations.AddField(
            model_name="trip",
            name="origin",
            field=models.CharField(default="null", max_length=100),
        ),
        migrations.AlterField(
            model_name="trip",
            name="addedTime",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 1, 15, 17, 26, 28, 869772)
            ),
        ),
        migrations.AlterField(
            model_name="trip",
            name="departureDate",
            field=models.DateTimeField(default=""),
        ),
    ]
